/**
 * TsPlanning
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 筺体冷却方法
 */
export type CoolingSystem = 0 | 1 | 2 | 4;

export const CoolingSystem = {
    NUMBER_0: 0 as CoolingSystem,
    NUMBER_1: 1 as CoolingSystem,
    NUMBER_2: 2 as CoolingSystem,
    NUMBER_4: 4 as CoolingSystem
};