/**
 * TsPlanning
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TsCalcContainerSpiceList { 
    /**
     * SpiceNetList文字列を取得または設定します
     */
    spiceNetList?: string;
    /**
     * 計算温度を取得または設定します
     */
    temperature?: Array<number>;
}