/**
 * TsPlanning
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TsCalcContainerPhysicality { 
    /**
     * 現時点での温度[℃]を取得または設定します。
     */
    temperature?: number;
    /**
     * 外気温度[℃]を取得または設定します。
     */
    temperatureAir?: number;
    /**
     * フィンなしの場合の温度[℃]を取得または設定します  ヒートシンク計算のみ使用します
     */
    temperatureBetweenFin?: number;
    /**
     * 空気の熱伝導率：常温時(320K)[W/m℃]を取得または設定します。
     */
    tCA320?: number;
    /**
     * 空気の動粘性係数[m<sup>2</sup>/s]を取得または設定します。
     */
    viSA?: number;
    /**
     * 動粘性係数の入力値を使用するか否か
     */
    isInputVISA?: boolean;
    /**
     * 空気のプラントル数を取得または設定します。
     */
    pRA?: number;
    /**
     * プラントル数の入力値を使用するか否か
     */
    isInputPRA?: boolean;
    /**
     * 空気の密度[kg/m<sup>3</sup>]を取得または設定します。
     */
    deNA?: number;
    /**
     * 密度の入力値を使用するか否か
     */
    isInputDENA?: boolean;
    /**
     * 空気の体膨張係数[1/℃]を取得または設定します。
     */
    veCA?: number;
    /**
     * 体膨張係数[1/℃]について、温度により変動しない固定値を使用するかどうか設定または取得します
     */
    isUseFixedVolumetricThermalExpansionCoefficient?: boolean;
    /**
     * フィン間空気の体膨張係数[1/℃]を取得または設定します。
     */
    veCFIN?: number;
    /**
     * 空気の定圧比熱[J/kg・℃]を取得又は設定します
     */
    sHCAP?: number;
    /**
     * 定圧比熱の入力値を使用するか否か
     */
    isInputSHCAP?: boolean;
    /**
     * 熱伝導率の入力値を使用するか否か
     */
    isInputTCA320?: boolean;
}