/**
 * TsPlanning
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CoolingSystem } from './coolingSystem';
import { TsCalcContainerPhysicality } from './tsCalcContainerPhysicality';

export interface TsCalcContainerCaseJudge { 
    /**
     * 温度上限[℃]を取得または設定します。
     */
    temperatureLimit?: number;
    /**
     * 外気温度[℃]を取得または設定します。
     */
    temperatureAir?: number;
    /**
     * 幅[m]を取得または設定します。
     */
    width?: number;
    /**
     * 奥行き[m]を取得または設定します。
     */
    depth?: number;
    /**
     * 高さ[m]を取得または設定します。
     */
    height?: number;
    /**
     * 排気口面積[m<sup>2</sup>]を取得または設定します。
     */
    areaExhaust?: number;
    /**
     * 吸気口面積[m<sup>2</sup>]を取得または設定します。
     */
    areaIntake?: number;
    /**
     * 消費電力[W]を取得または設定します。
     */
    power?: number;
    physicalityTable?: TsCalcContainerPhysicality;
    /**
     * 体積：複数、グラフ用の計算に使った体積を取得します。
     */
    readonly volumes?: Array<number>;
    /**
     * 消費電力：複数、筐体との接触の場合（グラフ用）を取得します
     */
    readonly powersContact?: Array<number>;
    /**
     * 体積：複数、筐体との非接触の場合（グラフ用）を取得します
     */
    readonly powersNoContact?: Array<number>;
    statusCoolingSystem?: CoolingSystem;
    /**
     * 筐体内部温度[℃]を取得します（自然空冷可否判断で行われる簡易計算です）
     */
    readonly temperature?: number;
    /**
     * 入力サイズの体積[m<sup>3</sup>]を参照します。
     */
    readonly volume?: number;
    /**
     * 有効排気口面積[m<sup>2</sup>]を取得します
     */
    readonly areaExhaustEffect?: number;
    /**
     * 温度マージン[℃]:筐体面接触有りを取得します
     */
    readonly temperatureMarginContact?: number;
    /**
     * 温度マージン[℃]:筐体面接触無しを取得します
     */
    readonly temperatureMarginNoContact?: number;
}