/**
 * TsPlanning
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TsCalcContainerSpiceList { 
    /**
     * SpiceNetList文字列を設定します
     */
    spiceNetList?: string;
    /**
     * 計算温度を取得します
     */
    readonly temperature?: Array<number>;
    /**
     * Node名＋計算温度を取得します
     */
    readonly nodeTempareture?: { [key: string]: number; };
    /**
     * 計算要素と熱コンダクタンスを取得します  値が設定されていない（Keyがない）要素についてはコンダクタンスが0となります
     */
    readonly element?: { [key: string]: { [key: string]: number; }; };
}